#!/bin/sh
#
# PROVIDE: minio
# REQUIRE: networking
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable minio:
# minio_bin_path (str):       Set to "/usr/local/bin/minio" by default.
#                             Provides the path to the minio server executable
#
# minio_config_path (str):    Set to "/etc/minio" by default.
#                             Defines the path for the configuration file minio will load on boot
#
# minio_run_user (str):       Set to "minio-user" by default.
#                             Defines the user that minio will run on
#
# minio_export_path (str):    Set to "/mnt/export" by default.
#                             Defines the path of files and folder to be exported by minio

. /etc/rc.subr

name="minio"
rcvar="${name}_enable"

load_rc_config $name
: ${minio_bin_path="/usr/local/bin/minio"}
: ${minio_config_path="/etc/minio"}
: ${minio_run_user="minio-user"}
: ${minio_export_path="/mnt/export"}

pidfile="/var/run/minio.pid"
logfile="/var/log/minio.log"

command="${minio_bin_path} --config-dir ${minio_config_path} server ${minio_export_path}"

start_cmd="minio_start"
status_cmd="minio_status"
stop_cmd="minio_stop"

minio_start() {
    echo "Starting ${name}..."
    /usr/sbin/daemon -u ${minio_run_user} -c -p ${pidfile} -f ${command}
}

minio_status() {
    if [ -f ${pidfile} ]; then
      echo "${name} is running as $(cat $pidfile)."
    else
      echo "${name} is not running."
      return 1
    fi
}

minio_stop() {
    if [ ! -f ${pidfile} ]; then
      echo "${name} is not running."
      return 1
    fi

    echo -n "Stopping ${name}..."
    kill -KILL $(cat $pidfile) 2> /dev/null && echo "stopped"
    rm -f ${pidfile}
}

run_rc_command "$1"
